- Management:
    - Proxmox:
        href: 'https://pve.<domain>.com'
        description: Server virtualization management
        icon: proxmox.svg
        widget:
          type: proxmox
          url: 'https://pve.<domain>.com'
          username: '{{HOMEPAGE_VAR_PROXMOX_USERNAME}}'
          password: '{{HOMEPAGE_VAR_PROXMOX_PASSWORD}}'
          node: pve
    - Traefik:
        href: 'https://traefik.<domain>.com'
        description: Proxy
        icon: traefik.png
        widget:
          type: traefik
          url: 'https://traefik.<domain>.com'
          username: '{{HOMEPAGE_VAR_TRAEFIK_USERNAME}}'
          password: '{{HOMEPAGE_VAR_TRAEFIK_PASSWORD}}'
    - Pihole:
        href: 'https://pihole.<domain>.com'
        description: DNS
        icon: pi-hole.png
#        widget:
#          type: pihole
#          url: 'http://pi.hole'
#          api: '{{HOMEPAGE_VAR_PIHOLE_API_KEY}}'
- Media:
    - Plex:
        href: 'https://plex.<domain>.com'
        description: Mediaserver
        icon: plex.png
        widget:
          type: plex
          url: http://plex:32400
          key: '{{HOMEPAGE_VAR_PLEX_API_KEY}}'
    - Overseerr:
        href: 'https://overseerr.<domain>.com'
        description: Media requests
        icon: overseerr.png
        widget:
          type: overseerr
          url: http://overseerr:5055
          key: '{{HOMEPAGE_VAR_OVERSEERR_API_KEY}}'
    - Sonarr:
        href: 'https://sonarr.<domain>.com'
        description: TV show collection manager
        icon: sonarr.png
        widget:
          type: sonarr
          url: http://sonarr:8989
          key: '{{HOMEPAGE_VAR_SONARR_API_KEY}}'
          enableQueue: true
    - Radarr:
        href: 'https://radarr.<domain>.com'
        description: Movie collection manager
        icon: radarr.png
        widget:
          type: radarr
          url: http://radarr:7878
          key: '{{HOMEPAGE_VAR_RADARR_API_KEY}}'
          enableQueue: true
    - Prowlarr:
        href: 'https://prowlarr.<domain>.com'
        description: index manager
        icon: prowlarr.png
        widget:
          type: prowlarr
          url: http://prowlarr:9696
          key: '{{HOMEPAGE_VAR_PROWLARR_API_KEY}}'
    - RealDebridClient:
        href: 'https://rdt.<domain>.com'
        description: Client for Real Debrid
        icon: real-debrid.png