apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: homelab-address-pool
  namespace: metallb-system
spec:
  addresses:
  - <IP_RANGE_FROM>-<IP_RANGE_TO>
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: homelab-l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - homelab-address-pool
